{
    "status": "failed", 
    "job_metadata": {
        "project_name": "Inova - Eastern Region", 
        "revit_version": "2024", 
        "hub_name": "Ballinger", 
        "timestamp": "2025-10-08T09:15:38.701000", 
        "job_id": "job_20251008_083949_34", 
        "model_name": "IAH_HOS_ALL_A_EXT_BA-EA_R24"
    }, 
    "logs": "=== PATH CONFIGURATION ===\n  Database folder: C:\\Users\\szhang\\Documents\\EnneadTab Ecosystem\\Dump\\RevitSlaveDatabase\n  Task output dir: C:\\Users\\szhang\\Documents\\EnneadTab Ecosystem\\Dump\\RevitSlaveDatabase\\task_output\n  Debug dir: C:\\Users\\szhang\\Documents\\EnneadTab Ecosystem\\Dump\\RevitSlaveDatabase\\_debug\n  Log dir: C:\\Users\\szhang\\Documents\\EnneadTab Ecosystem\\Dump\\RevitSlaveDatabase\\_log\nJob set to pending\nJob set to running\nException: 'unknown' codec can't decode byte 0xb6 in position 15: Unable to translate bytes [B6] at index 15 from specified code page to Unicode.", 
    "error_msg": "Traceback (most recent call last):\n  File \"C:\\Users\\szhang\\github\\EnneadTab-OS\\Apps\\_revit\\EnneaDuck.extension\\EnneadTab.tab\\Resource.panel\\revit_remote_server.pushbutton\\revit_remote_server_script.py\", line 619, in revit_remote_server\n    _append_debug(\"Health metrics completed with error: {}\".format(error_msg), paths)\n  File \"C:\\Users\\szhang\\github\\EnneadTab-OS\\Apps\\_revit\\EnneaDuck.extension\\EnneadTab.tab\\Resource.panel\\revit_remote_server.pushbutton\\revit_remote_server_script.py\", line 55, in _save_json\n    json.dump(data, f, indent=4)\n  File \"json\\__init__.py\", line 189, in dump\n  File \"json\\encoder.py\", line 434, in _iterencode\n  File \"json\\encoder.py\", line 408, in _iterencode_dict\n  File \"json\\encoder.py\", line 408, in _iterencode_dict\n  File \"json\\encoder.py\", line 408, in _iterencode_dict\n  File \"json\\encoder.py\", line 408, in _iterencode_dict\n  File \"json\\encoder.py\", line 332, in _iterencode_list\n  File \"json\\encoder.py\", line 390, in _iterencode_dict\n  File \"json\\encoder.py\", line 47, in py_encode_basestring_ascii\nUnicodeDecodeError: 'unknown' codec can't decode byte 0xb6 in position 15: Unable to translate bytes [B6] at index 15 from specified code page to Unicode.\n"
}